import type { IrCanvas, IrElement } from "@/lib/irFromFigma";

type GeneratedFile = { path: string; content: string; kind: "code" | "style" | "config" | "asset_index" };

function escapeJs(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function elementToJsx(el: IrElement) {
  if (el.kind === "rect") {
    const style: Record<string, any> = {
      position: "absolute",
      left: `${el.x}px`,
      top: `${el.y}px`,
      width: `${el.w}px`,
      height: `${el.h}px`,
      background: el.fill
    };
    if (el.stroke) {
      style.border = `${el.strokeWidth ?? 1}px solid ${el.stroke}`;
    }
    if (typeof el.radius === "number") {
      style.borderRadius = `${el.radius}px`;
    }
    return `<div data-figma-id="${escapeJs(el.id)}" style={${JSON.stringify(style)}} />`;
  }

  // text
  const style: Record<string, any> = {
    position: "absolute",
    left: `${el.x}px`,
    top: `${el.y}px`,
    width: `${el.w}px`,
    height: `${el.h}px`,
    color: el.color,
    fontSize: `${el.fontSize}px`,
    fontFamily: el.fontFamily ?? "Inter, system-ui, -apple-system, Segoe UI, Roboto, 'Noto Sans JP', sans-serif",
    fontWeight: el.fontWeight ?? 400,
    whiteSpace: "pre-wrap",
    overflow: "hidden"
  };
  if (el.align) style.textAlign = el.align;
  if (typeof el.lineHeightPx === "number") style.lineHeight = `${el.lineHeightPx}px`;

  return `<div data-figma-id="${escapeJs(el.id)}" style={${JSON.stringify(style)}}>${escapeJs(el.text)}</div>`;
}

export function codegenPixel(input: {
  canvas: IrCanvas;
  sourceUrl: string;
  figmaFileKey: string;
  figmaNodeId: string;
}) {
  const { canvas } = input;

  const readme = `# Generated by Design2Code Studio (Pixel Mode)

- Source: ${input.sourceUrl}
- FileKey: ${input.figmaFileKey}
- NodeId: ${input.figmaNodeId}

This output is a "pixel mode" scaffold.
- It aims for visual parity first (absolute layout).
- Next step: convert AutoLayout -> Flex/Grid and extract reusable components.
`;

  const pkg = `{
  "name": "generated-design2code",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.35",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  }
}
`;

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;
`;

  const globals = `html, body { height: 100%; }
body { margin: 0; font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, "Noto Sans JP", sans-serif; background: #0b0b10; }
* { box-sizing: border-box; }
`;

  const layout = `export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
`;

  // JSX生成（rectは先に、textは後にすると見た目が安定しやすい）
  const rects = canvas.elements.filter((e) => e.kind === "rect").map(elementToJsx).join("\n      ");
  const texts = canvas.elements.filter((e) => e.kind === "text").map(elementToJsx).join("\n      ");

  const page = `export default function Page() {
  return (
    <main style={{ minHeight: "100vh", padding: 24 }}>
      <div
        style={{
          position: "relative",
          width: ${Math.round(canvas.width)},
          height: ${Math.round(canvas.height)},
          margin: "0 auto",
          background: "${canvas.background ?? "rgba(0,0,0,0)"}",
          border: "1px solid rgba(255,255,255,0.10)",
          borderRadius: 16,
          overflow: "hidden",
        }}
      >
      ${rects}
      ${texts}
      </div>
    </main>
  );
}
`;

  const irJson = JSON.stringify(canvas, null, 2);

  const files: GeneratedFile[] = [
    { path: "README.md", content: readme, kind: "config" },
    { path: "package.json", content: pkg, kind: "config" },
    { path: "next.config.mjs", content: nextConfig, kind: "config" },
    { path: "app/layout.tsx", content: layout, kind: "code" },
    { path: "app/page.tsx", content: page, kind: "code" },
    { path: "app/globals.css", content: globals, kind: "style" },
    { path: "ir.canvas.json", content: irJson, kind: "asset_index" }
  ];

  // mapping は最小（ルート->page）
  const mappings = canvas.elements.slice(0, 200).map((el) => ({
    figma_node_id: el.id,
    figma_node_name: el.name,
    target_path: "app/page.tsx",
    target_symbol: null,
    loc_start: null,
    loc_end: null,
    mapping_type: (el.kind === "text" ? "element" : "element") as const
  }));

  return { files, mappings };
}
