import crypto from "crypto";
import { renderHtmlToPng, diffPngBuffers } from "@/lib/visualDiff";

function sha256(s: string) {
  return crypto.createHash("sha256").update(s).digest("hex");
}

/**
 * モックの生成パイプライン。
 * 本番では：Figma Fetch → Normalize → IR → Component Extract → Codegen → QC
 */
export async function runMockPipeline(input: {
  figmaFileKey: string;
  figmaNodeId: string;
  sourceUrl: string;
  profileOverrideId?: string;
  projectId: string;
  generationId: string;
}) {
  const snapshotHash = `sha256:${sha256(`${input.figmaFileKey}|${input.figmaNodeId}|${input.sourceUrl}`)}`;

  // IR（最低限）
  const ir = {
    irVersion: "1.0",
    source: {
      tool: "figma",
      fileKey: input.figmaFileKey,
      nodeId: input.figmaNodeId,
      nodeName: "MockFrame",
      url: input.sourceUrl,
      fetchedAt: new Date().toISOString(),
      snapshotHash
    },
    designTokens: {
      colors: { "color.primary.600": "#AA5AFF", "color.surface.0": "#121218" },
      spacing: { "space.4": 16, "space.6": 24 },
      radius: { "radius.md": 16 },
      shadow: { "shadow.sm": "0 10px 30px rgba(0,0,0,0.18)" },
      typography: {
        "type.h1": { fontFamily: "Inter", fontSize: 28, lineHeight: 36, fontWeight: 700 }
      },
      borderWidth: { "border.1": 1 }
    },
    assets: [],
    components: [],
    page: {
      name: "MockPage",
      root: {
        id: "n_root",
        figmaNodeId: input.figmaNodeId,
        name: "Frame",
        kind: "container",
        layout: { type: "flex", direction: "col", justify: "start", align: "stretch", gap: 16 },
        style: {
          padding: { top: 24, right: 24, bottom: 24, left: 24 },
          background: { type: "solid", value: "#121218" }
        },
        children: [
          {
            id: "n_title",
            figmaNodeId: "12:400",
            name: "Title",
            kind: "text",
            layout: { type: "flow" },
            style: {
              text: {
                content: "Generated (Mock) — Design2Code Studio",
                typographyToken: "type.h1",
                color: { type: "solid", value: "#AA5AFF" },
                align: "left"
              }
            }
          }
        ]
      }
    },
    meta: {
      generator: "Design2Code Studio",
      profile: {
        mode: "production",
        outputTarget: "nextjs_tailwind",
        useShadcn: true,
        stylingStrategy: "tailwind_only",
        namingConvention: "camel",
        tokenClusterThreshold: 0.12
      }
    }
  };

  // Report（最低限）
  const report = {
    summary: {
      tokenCoverageEstimate: 0.55,
      absoluteUsageEstimate: 0.05,
      duplicationCandidates: 0
    },
    unsupported: [],
    notes: [
      "This is a mock pipeline output. Replace with real Figma fetch + IR build.",
      "ZIP export and DB persistence are fully wired."
    ]
  };

  // 生成ファイル（Next.jsプロジェクト一式の“雛形”）
  const files = buildMockGeneratedProject(input, ir);

  // Mapping（最低限）
  const mappings = [
    {
      figma_node_id: input.figmaNodeId,
      figma_node_name: "Frame",
      target_path: "app/page.tsx",
      target_symbol: "Page",
      loc_start: 1,
      loc_end: 120,
      mapping_type: "component" as const
    },
    {
      figma_node_id: "12:400",
      figma_node_name: "Title",
      target_path: "app/page.tsx",
      target_symbol: null,
      loc_start: 10,
      loc_end: 18,
      mapping_type: "element" as const
    }
  ];

  return {
    snapshotHash,
    ir,
    report,
    profileSnapshot: ir.meta.profile,
    files,
    mappings
  };
}

function buildMockGeneratedProject(input: { figmaFileKey: string; figmaNodeId: string; sourceUrl: string }, ir: any) {
  const readme = `# Generated by Design2Code Studio (Mock)

This is a generated project scaffold.

- Source: ${input.sourceUrl}
- FileKey: ${input.figmaFileKey}
- NodeId: ${input.figmaNodeId}

Next step:
- Replace mock pipeline with real Figma fetch + IR + codegen.
`;

  const pkg = `{
  "name": "generated-design2code",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.14",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  }
}
`;

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;
`;

  const globals = `html, body { height: 100%; }
body { margin: 0; font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, "Noto Sans JP", sans-serif; }
`;

  const layout = `export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
`;

  const page = `export default function Page() {
  return (
    <main style={{ minHeight: "100vh", background: "#121218", color: "#F5F5FA", padding: 24 }}>
      <div style={{ maxWidth: 960, margin: "0 auto" }}>
        <h1 style={{ color: "#AA5AFF", fontSize: 28, lineHeight: "36px", margin: 0 }}>
          Generated (Mock) — Design2Code Studio
        </h1>
        <p style={{ opacity: 0.8, marginTop: 12 }}>
          This is a generated scaffold. Replace mock pipeline with real Figma conversion.
        </p>
        <div style={{ marginTop: 20, padding: 16, border: "1px solid rgba(255,255,255,0.12)", borderRadius: 16 }}>
          <div style={{ fontSize: 12, opacity: 0.7 }}>Source</div>
          <div style={{ marginTop: 6, wordBreak: "break-all" }}>${input.sourceUrl}</div>
        </div>
      </div>
    </main>
  );
}
`;

  const irJson = JSON.stringify(ir, null, 2);

  return [
    { path: "README.md", content: readme, kind: "config" as const },
    { path: "package.json", content: pkg, kind: "config" as const },
    { path: "next.config.mjs", content: nextConfig, kind: "config" as const },
    { path: "app/layout.tsx", content: layout, kind: "code" as const },
    { path: "app/page.tsx", content: page, kind: "code" as const },
    { path: "app/globals.css", content: globals, kind: "style" as const },
    { path: "ir.json", content: irJson, kind: "asset_index" as const }
  ];
}

/**
 * 生成されたコードをレンダリングして比較する（オプション）
 * - Figma Token がある場合のみ実行
 * - 生成されたHTMLをレンダリングしてPNG化し、Figma画像と比較
 */
export async function renderAndCompareGeneratedCode(params: {
  files: Array<{ path: string; content: string }>;
  figmaImageUrl: string | null;
  projectId: string;
  snapshotHash: string;
}): Promise<{ renderPng: Uint8Array | null; diffPng: Uint8Array | null; diffMeta: any }> {
  const { files, figmaImageUrl, projectId, snapshotHash } = params;

  // Figma画像が無い場合はスキップ
  if (!figmaImageUrl) {
    return { renderPng: null, diffPng: null, diffMeta: null };
  }

  try {
    // 生成されたHTMLを構築（app/page.tsx からHTMLを抽出）
    const pageFile = files.find((f) => f.path === "app/page.tsx");
    if (!pageFile) {
      console.warn("[renderAndCompareGeneratedCode] app/page.tsx が見つかりません");
      return { renderPng: null, diffPng: null, diffMeta: null };
    }

    // JSXからHTMLを構築（簡易版：実際のReactレンダリングは複雑なので、スタイルを抽出してHTML化）
    const html = buildHtmlFromGeneratedCode(pageFile.content, files);

    // HTMLをレンダリングしてPNG化
    const renderPng = await renderHtmlToPng({ html, width: 1280, height: 720 });

    // Figma画像を取得
    const figmaRes = await fetch(figmaImageUrl, { cache: "no-store" });
    if (!figmaRes.ok) {
      console.warn(`[renderAndCompareGeneratedCode] Figma画像の取得に失敗: ${figmaRes.status}`);
      return { renderPng, diffPng: null, diffMeta: null };
    }
    const figmaPng = new Uint8Array(await figmaRes.arrayBuffer());

    // 差分を計算
    const diff = await diffPngBuffers({ aPng: figmaPng, bPng: renderPng, threshold: 0.12 });
    const diffMeta = {
      diffRatio: diff.diffRatio,
      diffPixels: diff.diffPixels,
      totalPixels: diff.totalPixels,
      threshold: 0.12,
    };

    // Storageに保存
    const supabase = (await import("@/lib/supabaseAdmin")).getSupabaseAdmin();
    if (supabase) {
      // レンダリング結果を保存
      await supabase.storage
        .from("d2c-previews")
        .upload(`${projectId}/${snapshotHash}_render.png`, Buffer.from(renderPng), {
          contentType: "image/png",
          upsert: true,
        });

      // 差分画像を保存
      await supabase.storage
        .from("d2c-previews")
        .upload(`${projectId}/${snapshotHash}_diff.png`, Buffer.from(diff.diffPng), {
          contentType: "image/png",
          upsert: true,
        });
    }

    return { renderPng, diffPng: diff.diffPng, diffMeta };
  } catch (e) {
    console.error("[renderAndCompareGeneratedCode] レンダリング・比較処理でエラー:", e);
    return { renderPng: null, diffPng: null, diffMeta: null };
  }
}

/**
 * 生成されたコードからHTMLを構築（簡易版）
 * - JSXのスタイル属性を抽出してHTML化
 */
function buildHtmlFromGeneratedCode(pageContent: string, allFiles: Array<{ path: string; content: string }>): string {
  // globals.css を取得
  const globalsCss = allFiles.find((f) => f.path === "app/globals.css")?.content ?? "";

  // JSXからスタイルを抽出（簡易版：実際のReactレンダリングは複雑）
  // ここでは、インラインスタイルを抽出してHTML化
  const styleMatches = pageContent.match(/style=\{\{([^}]+)\}\}/g) || [];
  const inlineStyles = styleMatches.map((m) => {
    const content = m.replace(/style=\{\{|}\}/g, "").trim();
    // JSオブジェクト形式をCSSに変換（簡易版）
    return content
      .replace(/(\w+):\s*"([^"]+)"/g, '$1: $2')
      .replace(/(\w+):\s*(\d+)/g, "$1: $2px")
      .replace(/,/g, ";");
  });

  // HTMLを構築
  return `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    ${globalsCss}
    html, body { margin: 0; padding: 0; }
    * { box-sizing: border-box; }
  </style>
</head>
<body>
  <div style="${inlineStyles[0] || ""}">
    <h1 style="${inlineStyles[1] || ""}">Generated (Mock) — Design2Code Studio</h1>
    <p style="${inlineStyles[2] || ""}">This is a generated scaffold.</p>
  </div>
</body>
</html>`;
}
